title: Android OMH Storage
email: contact@openmobilehub.com
description: Android OMH Storage Official Documentation
baseurl: "/android-omh-storage/docs"
url: "https://openmobilehub.github.io"
github_username: openmobilehub

theme: just-the-docs

collections:
  plugins:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # collections:
  #   plugins:
  #     name: Plugins
  #     nav_fold: false
